config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins
  resources :charges
  devise_for :users
  root "pins#index"
  get "about" => "pages#about"
  get "team" => "pages#team"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

     validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :pins

	validates :name, presence: true
	validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params) 
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end  

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/charges/create_html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Laund_dis</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span> Home
           <% end %>  
        </li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Team", team_path %></li>
        <% if user_signed_in? %>
           <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
           </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-wrench"></span> Account Settings
             <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Log Out
             <% end %> 
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%=content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>	
	</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Launddis</h1>
	<p>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg"%>
	</p>
</div>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>To be continued</p>

app/views/pages/team.html.erb
<h1>Team</h1>
<p>Brought to you by </p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>            
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>  
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel- heading center">
			<%= image_tag @pin.image.url %>
		</div>
		<div class="panel-body">
		<p><%= @pin.description %></p>
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>

		
		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin) do %>            
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
			<% end%>
  		</div>
		</div>
	</div>
</div>